export const VALIDATION_STATUS_VALID = "0";
export const VALIDATION_STATUS_INVALID = "-1";
export const VALIDATION_STATUS_WAITING_DUPLICATE_VALIDATION = "1";
export const VALIDATION_STATUS_DUPLICATE_PHONE = "10";
export const VALIDATION_STATUS_DUPLICATE_EMAIL = "20";
export const VALIDATION_STATUS_INVALID_FIRST_NAME = "40";
export const VALIDATION_STATUS_INVALID_PHONE = "100";
export const VALIDATION_STATUS_INVALID_EMAIL = "200";
export const VALIDATION_STATUS_REJECTED_BY_STATE_PHONE = "400";
export const VALIDATION_STATUS_REJECTED_BY_STATE_EMAIL = "1000";
export const VALIDATION_STATUS_REJECTED_BY_SOURCE_CODE_PHONE = "2000";
export const VALIDATION_STATUS_REJECTED_BY_SOURCE_CODE_EMAIL = "4000";
export const VALIDATION_STATUS_CUSTOMIZED_ERROR = "10000";

export default {
  "VALIDATION_STATUS_VALID": "Valid",
  "VALIDATION_STATUS_INVALID": "Invalid",
  "VALIDATION_STATUS_DUPLICATE_PHONE": "Duplicate Phone",
  "VALIDATION_STATUS_DUPLICATE_EMAIL": "Duplicate Email",
  "VALIDATION_STATUS_INVALID_FIRST_NAME": "Invalid First Name",
  "VALIDATION_STATUS_INVALID_PHONE": "Invalid Phone",
  "VALIDATION_STATUS_INVALID_EMAIL": "Invalid Email",
  "VALIDATION_STATUS_REJECTED_BY_STATE_PHONE": "Rejected By State&Phone",
  "VALIDATION_STATUS_REJECTED_BY_STATE_EMAIL": "Rejected By State&Email",
  "VALIDATION_STATUS_REJECTED_BY_SOURCE_CODE_PHONE": "Rejected By SourceCode&Phone",
  "VALIDATION_STATUS_REJECTED_BY_SOURCE_CODE_EMAIL": "Rejected By SourceCode&Email",
  "VALIDATION_STATUS_CUSTOMIZED_ERROR": "Error"
}