export default {
    "0": "Unknown",
    "1": "Api",
    "2": "Manual",
    "3": "Funnel",
    "4": "Import File",
    "5": "Add To Campaign Step",
    "6": "From Call List",
    "7": "Web",
    "8": "Tag Event",
    "9": "Conversion Event",
    "10": "Konnective",
    "11": "Order",
    "12": "Ping Tree Sold Event",
    "13": "Ping Tree Unsold Event",
    "14": "New User Event",
    "15": "Forget Password Event",
    "16": "Input Contact",
    "17": "Schema Contact",
    "18": "Form Contact",
    "19": "Call Flow",
    "20": "Internal Trigger",
    "21": "User Request"
}