export default{
    "0": "other",
    "1": "Created",
    "2": "Scheduled",
    "3": "Rescheduled",
    "4": "Cancelled",
    "5": "Charged",
    "6": "Refunded",
    "7": "Order Fulfillment",
    "8": "Product Fulfillment",
    "9": "Product Added",
    "10": "Product Removed",
    "11": "Tag Added",
    "12": "Tag Removed",
    "13": "Comment",    
    "14": "Subscription Created",
    "15": "Payment Captured",
    "16": "Charged Failed",
    "17": "Coupon Redeem",
    "18": "Chargeback",
    "19": "Payment Capture Failed",
  }