export default {
  "0": "Active",
  "1": "Created",
  "2": "Paused",
  "3": "Cancelled",
  "4": "Expired",
  "5": "Failed",
  "10": "In trial",
  "11": "Setup Failed",
  "12": "Verify Failed",
  "20": "Charged",
  "21": "Refuned",
  "22": "Refuned Partially",
  "23": "Dunning",
  "24": "Authorized",
};